---
# defaults file for discourse

## Git url to pull discourse_docker from
discourse_docker_git: 'https://github.com/discourse/discourse_docker.git'

## Which Git revision should this container use? (default: tests-passed)
## You can use one of three branches: 'stable', 'tests-passed' and 'master'
## Read more: https://meta.discourse.org/t/change-tracking-branch-for-your-discourse-instance/17014/1
git_branch: 'tests-passed'

## Set db_shared_buffers to 1/3 of the memory you wish to allocate to postgres
## on 1GB install set to 128MB on a 4GB instance you may raise to 1GB
pg_mem: "128MB"

## How many concurrent web requests are to be supported
unicorn_workers: 2

## List of comma delimited emails that will be made admin and developer
## on initial signup example 'user1@example.com,user2@example.com'
discourse_developer_emails: 'me@example.com'

## The domain name this Discourse instance will respond to
discourse_hostname: 'discourse.example.com'

## The mailserver this Discourse instance will use
discourse_smtp_address: smtp.example.com
discourse_smtp_port: 587
discourse_smtp_user_name: user@example.com
discourse_smtp_password: "pa$$word"

## The CDN address for this Discourse instance (configured to pull)
discourse_cdn_url: //discourse-cdn.example.com

