---
# tasks file for docker

- name: Install apt-transport-https
  apt: name=apt-transport-https state=present

- name: Add the docker repository key
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add docker repository
  apt_repository: >
    repo='deb https://get.docker.com/ubuntu docker main'
    state=present

- name: Install docker
  apt: name=lxc-docker state=latest update_cache=yes
